USE movie_recommender;

INSERT INTO movies (title, poster_path, overview, release_year, vote_average, runtime, director, actors, genre) VALUES
('The Shawshank Redemption', NULL, 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an pointedly warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates for his persistence and good nature.', 1994, 9.3, 142, 'Frank Darabont', 'Tim Robbins, Morgan Freeman, Bob Gunton', 'Drama'),
('The Dark Knight', NULL, 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.', 2008, 9.0, 152, 'Christopher Nolan', 'Christian Bale, Heath Ledger, Aaron Eckhart', 'Action'),
('Inception', NULL, 'Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets, is offered a chance to regain his old life as payment for a task considered to be impossible: inception.', 2010, 8.8, 148, 'Christopher Nolan', 'Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page', 'Sci-Fi'),
('Pulp Fiction', NULL, 'A burger-loving hit man, his philosophical partner, a drug-addled gangster''s moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.', 1994, 8.9, 154, 'Quentin Tarantino', 'John Travolta, Uma Thurman, Samuel L. Jackson', 'Crime'),
('The Matrix', NULL, 'Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.', 1999, 8.7, 136, 'Lana Wachowski, Lilly Wachowski', 'Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss', 'Sci-Fi'),
('Interstellar', NULL, 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.', 2014, 8.7, 169, 'Christopher Nolan', 'Matthew McConaughey, Anne Hathaway, Jessica Chastain', 'Sci-Fi'),
('Parasite', NULL, 'All unemployed, Ki-taek''s family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.', 2019, 8.5, 132, 'Bong Joon-ho', 'Kang-ho Song, Sun-kyun Lee, Yeo-jeong Jo', 'Thriller'),
('Spirited Away', NULL, 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.', 2001, 8.6, 125, 'Hayao Miyazaki', 'Rumi Hiiragi, Miyu Irino, Mari Natsuki', 'Animation'),
('The Godfather', NULL, 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch Vito Corleone barely survives an attempt on his life, his youngest son Michael steps in.', 1972, 9.2, 175, 'Francis Ford Coppola', 'Marlon Brando, Al Pacino, James Caan', 'Crime'),
('Avengers: Endgame', NULL, 'After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos'' actions and restore balance to the universe.', 2019, 8.4, 181, 'Anthony Russo, Joe Russo', 'Robert Downey Jr., Chris Evans, Mark Ruffalo', 'Action'),
('Get Out', NULL, 'Chris and his girlfriend Rose go upstate to visit her parents for the weekend. At first, Chris reads the family''s overly accommodating behavior as nervous attempts to deal with their daughter''s interracial relationship, but as the weekend progresses, a series of increasingly disturbing discoveries lead him to a truth that he never could have imagined.', 2017, 7.7, 104, 'Jordan Peele', 'Daniel Kaluuya, Allison Williams, Bradley Whitford', 'Horror'),
('La La Land', NULL, 'Sebastian and Mia are drawn together by their common desire to do what they love. But as success mounts, they are faced with decisions that begin to fray the fragile fabric of their love affair, and the dreams they worked so hard to maintain in each other threaten to rip them apart.', 2016, 8.0, 128, 'Damien Chazelle', 'Ryan Gosling, Emma Stone, John Legend', 'Romance'),
('Mad Max: Fury Road', NULL, 'An apocalyptic story set in the furthest reaches of our planet, in a stark desert landscape where humanity is broken, and most everyone is crazed fighting for the necessities of life. Within this world exist two rebels on the run who just might be able to restore order.', 2015, 8.1, 120, 'George Miller', 'Tom Hardy, Charlize Theron, Nicholas Hoult', 'Action'),
('The Grand Budapest Hotel', NULL, 'The Grand Budapest Hotel tells of a legendary concierge at a famous European hotel between the wars and his friendship with a young employee who becomes his trusted protégé. The story involves the theft and recovery of a priceless Renaissance painting.', 2014, 8.1, 99, 'Wes Anderson', 'Ralph Fiennes, F. Murray Abraham, Mathieu Amalric', 'Comedy'),
('Joker', NULL, 'During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.', 2019, 8.3, 122, 'Todd Phillips', 'Joaquin Phoenix, Robert De Niro, Zazie Beetz', 'Drama');